const Menu=[
    {
        id:1,
        name:'Chapathi',
        category:"dinner",
        price:"220$",
        img:"./Images/chapathi.jpg"
    },
    {
        id:2,
        name:'Corn',
        category:"evening",
        price:"120$",
        img:"./Images/corn1.jpg"
    },
    {
        id:3,
        name:'Dhosa',
        category:"breakfast",
        price:"170$",
        img:"./Images/dhosa.jpg"
    },
    {
        id:4,
        name:'Idli',
        category:"breakfast",
        price:"260$",
        img:"./Images/idli.jpg"
    },
    {
        id:5,
        name:'FullMeals',
        category:"lunch",
        price:"230$",
        img:"./Images/lunch.jpg"
    },
    {
        id:6,
        name:'Meals',
        category:"lunch",
        price:"410$",
        img:"./Images/lunch1.jpg"
    },
    {
        id:7,
        name:'SambharRice',
        category:"lunch",
        price:"280$",
        img:"./Images/lunch3.jpg"
    },
    {
        id:8,
        name:'Parata',
        category:"dinner",
        price:"210$",
        img:"./Images/parata.jpg"   
    },
    {
        id:8,
        name:'Pizza',
        category:"evening",
        price:"480$",
        img:"./Images/pizza.jpg"
    },
    {
        id:9,
        name:'Pulav',
        category:"dinner",
        price:"310$",
        img:"./Images/pulav.jpg"
    },
    {
        id:10,
        name:'Samosa',
        category:"evening",
        price:"180$",
        img:"./Images/samosa.jpg"
    },
    {
        id:11,
        name:'Vada',
        category:"breakfast",
        price:"195$",
        img:"./Images/vada.jpg"
    }

]
export default Menu